/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrainsRouteImport } from './routes/strains'
import { Route as StockistsRouteImport } from './routes/stockists'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WholesaleIndexRouteImport } from './routes/wholesale.index'
import { Route as WholesaleLoginRouteImport } from './routes/wholesale.login'
import { Route as WholesaleDashboardRouteImport } from './routes/wholesale.dashboard'
import { Route as StrainSlugRouteImport } from './routes/strain.$slug'
import { Route as ShopInfusedPreRollsRouteImport } from './routes/shop.infused-pre-rolls'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalShippingRouteImport } from './routes/legal.shipping'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCannabisDisclaimerRouteImport } from './routes/legal.cannabis-disclaimer'
import { Route as AccountResetPasswordRouteImport } from './routes/account.reset-password'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountForgotPasswordRouteImport } from './routes/account.forgot-password'
import { Route as WholesaleDashboardIndexRouteImport } from './routes/wholesale.dashboard.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as WholesaleDashboardCheckoutRouteImport } from './routes/wholesale.dashboard.checkout'
import { Route as WholesaleDashboardCatalogRouteImport } from './routes/wholesale.dashboard.catalog'
import { Route as ApiPublicWholesaleApprovalEmailRouteImport } from './routes/api/public/wholesale-approval-email'
import { Route as ApiPublicBobpayWebhookRouteImport } from './routes/api/public/bobpay-webhook'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account.settings'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account.addresses'
import { Route as WholesaleDashboardOrdersIndexRouteImport } from './routes/wholesale.dashboard.orders.index'
import { Route as AuthenticatedAccountOrdersIndexRouteImport } from './routes/_authenticated/account.orders.index'
import { Route as WholesaleDashboardOrdersIdRouteImport } from './routes/wholesale.dashboard.orders.$id'
import { Route as AdminStrainsIdEditRouteImport } from './routes/admin.strains.$id.edit'
import { Route as AuthenticatedAccountOrdersOrderNumberRouteImport } from './routes/_authenticated/account.orders.$orderNumber'

const StrainsRoute = StrainsRouteImport.update({
  id: '/strains',
  path: '/strains',
  getParentRoute: () => rootRouteImport,
} as any)
const StockistsRoute = StockistsRouteImport.update({
  id: '/stockists',
  path: '/stockists',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleIndexRoute = WholesaleIndexRouteImport.update({
  id: '/wholesale/',
  path: '/wholesale/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleLoginRoute = WholesaleLoginRouteImport.update({
  id: '/wholesale/login',
  path: '/wholesale/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleDashboardRoute = WholesaleDashboardRouteImport.update({
  id: '/wholesale/dashboard',
  path: '/wholesale/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StrainSlugRoute = StrainSlugRouteImport.update({
  id: '/strain/$slug',
  path: '/strain/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopInfusedPreRollsRoute = ShopInfusedPreRollsRouteImport.update({
  id: '/infused-pre-rolls',
  path: '/infused-pre-rolls',
  getParentRoute: () => ShopRoute,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalShippingRoute = LegalShippingRouteImport.update({
  id: '/legal/shipping',
  path: '/legal/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCannabisDisclaimerRoute = LegalCannabisDisclaimerRouteImport.update({
  id: '/legal/cannabis-disclaimer',
  path: '/legal/cannabis-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleDashboardIndexRoute = WholesaleDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WholesaleDashboardRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const WholesaleDashboardCheckoutRoute =
  WholesaleDashboardCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => WholesaleDashboardRoute,
  } as any)
const WholesaleDashboardCatalogRoute =
  WholesaleDashboardCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => WholesaleDashboardRoute,
  } as any)
const ApiPublicWholesaleApprovalEmailRoute =
  ApiPublicWholesaleApprovalEmailRouteImport.update({
    id: '/api/public/wholesale-approval-email',
    path: '/api/public/wholesale-approval-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBobpayWebhookRoute = ApiPublicBobpayWebhookRouteImport.update({
  id: '/api/public/bobpay-webhook',
  path: '/api/public/bobpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/account/addresses',
    path: '/account/addresses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const WholesaleDashboardOrdersIndexRoute =
  WholesaleDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => WholesaleDashboardRoute,
  } as any)
const AuthenticatedAccountOrdersIndexRoute =
  AuthenticatedAccountOrdersIndexRouteImport.update({
    id: '/account/orders/',
    path: '/account/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const WholesaleDashboardOrdersIdRoute =
  WholesaleDashboardOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => WholesaleDashboardRoute,
  } as any)
const AdminStrainsIdEditRoute = AdminStrainsIdEditRouteImport.update({
  id: '/admin/strains/$id/edit',
  path: '/admin/strains/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountOrdersOrderNumberRoute =
  AuthenticatedAccountOrdersOrderNumberRouteImport.update({
    id: '/account/orders/$orderNumber',
    path: '/account/orders/$orderNumber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stockists': typeof StockistsRoute
  '/strains': typeof StrainsRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/legal/cannabis-disclaimer': typeof LegalCannabisDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/shop/infused-pre-rolls': typeof ShopInfusedPreRollsRoute
  '/strain/$slug': typeof StrainSlugRoute
  '/wholesale/dashboard': typeof WholesaleDashboardRouteWithChildren
  '/wholesale/login': typeof WholesaleLoginRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/api/public/bobpay-webhook': typeof ApiPublicBobpayWebhookRoute
  '/api/public/wholesale-approval-email': typeof ApiPublicWholesaleApprovalEmailRoute
  '/wholesale/dashboard/catalog': typeof WholesaleDashboardCatalogRoute
  '/wholesale/dashboard/checkout': typeof WholesaleDashboardCheckoutRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/wholesale/dashboard/': typeof WholesaleDashboardIndexRoute
  '/account/orders/$orderNumber': typeof AuthenticatedAccountOrdersOrderNumberRoute
  '/admin/strains/$id/edit': typeof AdminStrainsIdEditRoute
  '/wholesale/dashboard/orders/$id': typeof WholesaleDashboardOrdersIdRoute
  '/account/orders/': typeof AuthenticatedAccountOrdersIndexRoute
  '/wholesale/dashboard/orders/': typeof WholesaleDashboardOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stockists': typeof StockistsRoute
  '/strains': typeof StrainsRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/legal/cannabis-disclaimer': typeof LegalCannabisDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/shop/infused-pre-rolls': typeof ShopInfusedPreRollsRoute
  '/strain/$slug': typeof StrainSlugRoute
  '/wholesale/login': typeof WholesaleLoginRoute
  '/wholesale': typeof WholesaleIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/api/public/bobpay-webhook': typeof ApiPublicBobpayWebhookRoute
  '/api/public/wholesale-approval-email': typeof ApiPublicWholesaleApprovalEmailRoute
  '/wholesale/dashboard/catalog': typeof WholesaleDashboardCatalogRoute
  '/wholesale/dashboard/checkout': typeof WholesaleDashboardCheckoutRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/wholesale/dashboard': typeof WholesaleDashboardIndexRoute
  '/account/orders/$orderNumber': typeof AuthenticatedAccountOrdersOrderNumberRoute
  '/admin/strains/$id/edit': typeof AdminStrainsIdEditRoute
  '/wholesale/dashboard/orders/$id': typeof WholesaleDashboardOrdersIdRoute
  '/account/orders': typeof AuthenticatedAccountOrdersIndexRoute
  '/wholesale/dashboard/orders': typeof WholesaleDashboardOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stockists': typeof StockistsRoute
  '/strains': typeof StrainsRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/legal/cannabis-disclaimer': typeof LegalCannabisDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/shop/infused-pre-rolls': typeof ShopInfusedPreRollsRoute
  '/strain/$slug': typeof StrainSlugRoute
  '/wholesale/dashboard': typeof WholesaleDashboardRouteWithChildren
  '/wholesale/login': typeof WholesaleLoginRoute
  '/wholesale/': typeof WholesaleIndexRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/api/public/bobpay-webhook': typeof ApiPublicBobpayWebhookRoute
  '/api/public/wholesale-approval-email': typeof ApiPublicWholesaleApprovalEmailRoute
  '/wholesale/dashboard/catalog': typeof WholesaleDashboardCatalogRoute
  '/wholesale/dashboard/checkout': typeof WholesaleDashboardCheckoutRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/wholesale/dashboard/': typeof WholesaleDashboardIndexRoute
  '/_authenticated/account/orders/$orderNumber': typeof AuthenticatedAccountOrdersOrderNumberRoute
  '/admin/strains/$id/edit': typeof AdminStrainsIdEditRoute
  '/wholesale/dashboard/orders/$id': typeof WholesaleDashboardOrdersIdRoute
  '/_authenticated/account/orders/': typeof AuthenticatedAccountOrdersIndexRoute
  '/wholesale/dashboard/orders/': typeof WholesaleDashboardOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/shop'
    | '/sitemap.xml'
    | '/stockists'
    | '/strains'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/legal/cannabis-disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/shipping'
    | '/legal/terms'
    | '/order/$orderNumber'
    | '/shop/infused-pre-rolls'
    | '/strain/$slug'
    | '/wholesale/dashboard'
    | '/wholesale/login'
    | '/wholesale/'
    | '/account/addresses'
    | '/account/settings'
    | '/api/public/bobpay-webhook'
    | '/api/public/wholesale-approval-email'
    | '/wholesale/dashboard/catalog'
    | '/wholesale/dashboard/checkout'
    | '/account/'
    | '/wholesale/dashboard/'
    | '/account/orders/$orderNumber'
    | '/admin/strains/$id/edit'
    | '/wholesale/dashboard/orders/$id'
    | '/account/orders/'
    | '/wholesale/dashboard/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/shop'
    | '/sitemap.xml'
    | '/stockists'
    | '/strains'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/legal/cannabis-disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/shipping'
    | '/legal/terms'
    | '/order/$orderNumber'
    | '/shop/infused-pre-rolls'
    | '/strain/$slug'
    | '/wholesale/login'
    | '/wholesale'
    | '/account/addresses'
    | '/account/settings'
    | '/api/public/bobpay-webhook'
    | '/api/public/wholesale-approval-email'
    | '/wholesale/dashboard/catalog'
    | '/wholesale/dashboard/checkout'
    | '/account'
    | '/wholesale/dashboard'
    | '/account/orders/$orderNumber'
    | '/admin/strains/$id/edit'
    | '/wholesale/dashboard/orders/$id'
    | '/account/orders'
    | '/wholesale/dashboard/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/checkout'
    | '/shop'
    | '/sitemap.xml'
    | '/stockists'
    | '/strains'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/legal/cannabis-disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/shipping'
    | '/legal/terms'
    | '/order/$orderNumber'
    | '/shop/infused-pre-rolls'
    | '/strain/$slug'
    | '/wholesale/dashboard'
    | '/wholesale/login'
    | '/wholesale/'
    | '/_authenticated/account/addresses'
    | '/_authenticated/account/settings'
    | '/api/public/bobpay-webhook'
    | '/api/public/wholesale-approval-email'
    | '/wholesale/dashboard/catalog'
    | '/wholesale/dashboard/checkout'
    | '/_authenticated/account/'
    | '/wholesale/dashboard/'
    | '/_authenticated/account/orders/$orderNumber'
    | '/admin/strains/$id/edit'
    | '/wholesale/dashboard/orders/$id'
    | '/_authenticated/account/orders/'
    | '/wholesale/dashboard/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StockistsRoute: typeof StockistsRoute
  StrainsRoute: typeof StrainsRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  LegalCannabisDisclaimerRoute: typeof LegalCannabisDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalShippingRoute: typeof LegalShippingRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  StrainSlugRoute: typeof StrainSlugRoute
  WholesaleDashboardRoute: typeof WholesaleDashboardRouteWithChildren
  WholesaleLoginRoute: typeof WholesaleLoginRoute
  WholesaleIndexRoute: typeof WholesaleIndexRoute
  ApiPublicBobpayWebhookRoute: typeof ApiPublicBobpayWebhookRoute
  ApiPublicWholesaleApprovalEmailRoute: typeof ApiPublicWholesaleApprovalEmailRoute
  AdminStrainsIdEditRoute: typeof AdminStrainsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strains': {
      id: '/strains'
      path: '/strains'
      fullPath: '/strains'
      preLoaderRoute: typeof StrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stockists': {
      id: '/stockists'
      path: '/stockists'
      fullPath: '/stockists'
      preLoaderRoute: typeof StockistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/': {
      id: '/wholesale/'
      path: '/wholesale'
      fullPath: '/wholesale/'
      preLoaderRoute: typeof WholesaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/login': {
      id: '/wholesale/login'
      path: '/wholesale/login'
      fullPath: '/wholesale/login'
      preLoaderRoute: typeof WholesaleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/dashboard': {
      id: '/wholesale/dashboard'
      path: '/wholesale/dashboard'
      fullPath: '/wholesale/dashboard'
      preLoaderRoute: typeof WholesaleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strain/$slug': {
      id: '/strain/$slug'
      path: '/strain/$slug'
      fullPath: '/strain/$slug'
      preLoaderRoute: typeof StrainSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/infused-pre-rolls': {
      id: '/shop/infused-pre-rolls'
      path: '/infused-pre-rolls'
      fullPath: '/shop/infused-pre-rolls'
      preLoaderRoute: typeof ShopInfusedPreRollsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/shipping': {
      id: '/legal/shipping'
      path: '/legal/shipping'
      fullPath: '/legal/shipping'
      preLoaderRoute: typeof LegalShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cannabis-disclaimer': {
      id: '/legal/cannabis-disclaimer'
      path: '/legal/cannabis-disclaimer'
      fullPath: '/legal/cannabis-disclaimer'
      preLoaderRoute: typeof LegalCannabisDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/dashboard/': {
      id: '/wholesale/dashboard/'
      path: '/'
      fullPath: '/wholesale/dashboard/'
      preLoaderRoute: typeof WholesaleDashboardIndexRouteImport
      parentRoute: typeof WholesaleDashboardRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wholesale/dashboard/checkout': {
      id: '/wholesale/dashboard/checkout'
      path: '/checkout'
      fullPath: '/wholesale/dashboard/checkout'
      preLoaderRoute: typeof WholesaleDashboardCheckoutRouteImport
      parentRoute: typeof WholesaleDashboardRoute
    }
    '/wholesale/dashboard/catalog': {
      id: '/wholesale/dashboard/catalog'
      path: '/catalog'
      fullPath: '/wholesale/dashboard/catalog'
      preLoaderRoute: typeof WholesaleDashboardCatalogRouteImport
      parentRoute: typeof WholesaleDashboardRoute
    }
    '/api/public/wholesale-approval-email': {
      id: '/api/public/wholesale-approval-email'
      path: '/api/public/wholesale-approval-email'
      fullPath: '/api/public/wholesale-approval-email'
      preLoaderRoute: typeof ApiPublicWholesaleApprovalEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bobpay-webhook': {
      id: '/api/public/bobpay-webhook'
      path: '/api/public/bobpay-webhook'
      fullPath: '/api/public/bobpay-webhook'
      preLoaderRoute: typeof ApiPublicBobpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wholesale/dashboard/orders/': {
      id: '/wholesale/dashboard/orders/'
      path: '/orders'
      fullPath: '/wholesale/dashboard/orders/'
      preLoaderRoute: typeof WholesaleDashboardOrdersIndexRouteImport
      parentRoute: typeof WholesaleDashboardRoute
    }
    '/_authenticated/account/orders/': {
      id: '/_authenticated/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AuthenticatedAccountOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/wholesale/dashboard/orders/$id': {
      id: '/wholesale/dashboard/orders/$id'
      path: '/orders/$id'
      fullPath: '/wholesale/dashboard/orders/$id'
      preLoaderRoute: typeof WholesaleDashboardOrdersIdRouteImport
      parentRoute: typeof WholesaleDashboardRoute
    }
    '/admin/strains/$id/edit': {
      id: '/admin/strains/$id/edit'
      path: '/admin/strains/$id/edit'
      fullPath: '/admin/strains/$id/edit'
      preLoaderRoute: typeof AdminStrainsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/orders/$orderNumber': {
      id: '/_authenticated/account/orders/$orderNumber'
      path: '/account/orders/$orderNumber'
      fullPath: '/account/orders/$orderNumber'
      preLoaderRoute: typeof AuthenticatedAccountOrdersOrderNumberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountOrdersOrderNumberRoute: typeof AuthenticatedAccountOrdersOrderNumberRoute
  AuthenticatedAccountOrdersIndexRoute: typeof AuthenticatedAccountOrdersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountOrdersOrderNumberRoute:
    AuthenticatedAccountOrdersOrderNumberRoute,
  AuthenticatedAccountOrdersIndexRoute: AuthenticatedAccountOrdersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ShopRouteChildren {
  ShopInfusedPreRollsRoute: typeof ShopInfusedPreRollsRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopInfusedPreRollsRoute: ShopInfusedPreRollsRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface WholesaleDashboardRouteChildren {
  WholesaleDashboardCatalogRoute: typeof WholesaleDashboardCatalogRoute
  WholesaleDashboardCheckoutRoute: typeof WholesaleDashboardCheckoutRoute
  WholesaleDashboardIndexRoute: typeof WholesaleDashboardIndexRoute
  WholesaleDashboardOrdersIdRoute: typeof WholesaleDashboardOrdersIdRoute
  WholesaleDashboardOrdersIndexRoute: typeof WholesaleDashboardOrdersIndexRoute
}

const WholesaleDashboardRouteChildren: WholesaleDashboardRouteChildren = {
  WholesaleDashboardCatalogRoute: WholesaleDashboardCatalogRoute,
  WholesaleDashboardCheckoutRoute: WholesaleDashboardCheckoutRoute,
  WholesaleDashboardIndexRoute: WholesaleDashboardIndexRoute,
  WholesaleDashboardOrdersIdRoute: WholesaleDashboardOrdersIdRoute,
  WholesaleDashboardOrdersIndexRoute: WholesaleDashboardOrdersIndexRoute,
}

const WholesaleDashboardRouteWithChildren =
  WholesaleDashboardRoute._addFileChildren(WholesaleDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StockistsRoute: StockistsRoute,
  StrainsRoute: StrainsRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  LegalCannabisDisclaimerRoute: LegalCannabisDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalShippingRoute: LegalShippingRoute,
  LegalTermsRoute: LegalTermsRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  StrainSlugRoute: StrainSlugRoute,
  WholesaleDashboardRoute: WholesaleDashboardRouteWithChildren,
  WholesaleLoginRoute: WholesaleLoginRoute,
  WholesaleIndexRoute: WholesaleIndexRoute,
  ApiPublicBobpayWebhookRoute: ApiPublicBobpayWebhookRoute,
  ApiPublicWholesaleApprovalEmailRoute: ApiPublicWholesaleApprovalEmailRoute,
  AdminStrainsIdEditRoute: AdminStrainsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
