/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as StrainsRouteImport } from './routes/strains'
import { Route as StockistsRouteImport } from './routes/stockists'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StrainSlugRouteImport } from './routes/strain.$slug'
import { Route as ApiPublicBobpayWebhookRouteImport } from './routes/api/public/bobpay-webhook'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const StrainsRoute = StrainsRouteImport.update({
  id: '/strains',
  path: '/strains',
  getParentRoute: () => rootRouteImport,
} as any)
const StockistsRoute = StockistsRouteImport.update({
  id: '/stockists',
  path: '/stockists',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrainSlugRoute = StrainSlugRouteImport.update({
  id: '/strain/$slug',
  path: '/strain/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBobpayWebhookRoute = ApiPublicBobpayWebhookRouteImport.update({
  id: '/api/public/bobpay-webhook',
  path: '/api/public/bobpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/stockists': typeof StockistsRoute
  '/strains': typeof StrainsRoute
  '/wholesale': typeof WholesaleRoute
  '/strain/$slug': typeof StrainSlugRoute
  '/api/public/bobpay-webhook': typeof ApiPublicBobpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/stockists': typeof StockistsRoute
  '/strains': typeof StrainsRoute
  '/wholesale': typeof WholesaleRoute
  '/strain/$slug': typeof StrainSlugRoute
  '/api/public/bobpay-webhook': typeof ApiPublicBobpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/stockists': typeof StockistsRoute
  '/strains': typeof StrainsRoute
  '/wholesale': typeof WholesaleRoute
  '/strain/$slug': typeof StrainSlugRoute
  '/api/public/bobpay-webhook': typeof ApiPublicBobpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/shop'
    | '/stockists'
    | '/strains'
    | '/wholesale'
    | '/strain/$slug'
    | '/api/public/bobpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/shop'
    | '/stockists'
    | '/strains'
    | '/wholesale'
    | '/strain/$slug'
    | '/api/public/bobpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/shop'
    | '/stockists'
    | '/strains'
    | '/wholesale'
    | '/strain/$slug'
    | '/api/public/bobpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRoute
  StockistsRoute: typeof StockistsRoute
  StrainsRoute: typeof StrainsRoute
  WholesaleRoute: typeof WholesaleRoute
  StrainSlugRoute: typeof StrainSlugRoute
  ApiPublicBobpayWebhookRoute: typeof ApiPublicBobpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strains': {
      id: '/strains'
      path: '/strains'
      fullPath: '/strains'
      preLoaderRoute: typeof StrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stockists': {
      id: '/stockists'
      path: '/stockists'
      fullPath: '/stockists'
      preLoaderRoute: typeof StockistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strain/$slug': {
      id: '/strain/$slug'
      path: '/strain/$slug'
      fullPath: '/strain/$slug'
      preLoaderRoute: typeof StrainSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bobpay-webhook': {
      id: '/api/public/bobpay-webhook'
      path: '/api/public/bobpay-webhook'
      fullPath: '/api/public/bobpay-webhook'
      preLoaderRoute: typeof ApiPublicBobpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRoute,
  StockistsRoute: StockistsRoute,
  StrainsRoute: StrainsRoute,
  WholesaleRoute: WholesaleRoute,
  StrainSlugRoute: StrainSlugRoute,
  ApiPublicBobpayWebhookRoute: ApiPublicBobpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
